import { Router } from 'express';
import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken';
import { requireAuth, optionalAuth } from '../middleware/auth';
import { env } from '../config/env';
import { prisma } from '../config/database';

const router = Router();

/**
 * GET /api/auth/me
 * Get current authenticated user
 */
router.get('/me', optionalAuth, (req, res) => {
  if (!req.user) {
    res.status(401).json({ error: 'unauthorized', message: 'Not authenticated' });
    return;
  }

  res.json({
    id: req.user.id,
    email: req.user.email,
    walletId: req.user.walletId,
  });
});

/**
 * POST /api/auth/logout
 * Log out the current user
 */
router.post('/logout', (req, res) => {
  req.session.destroy((err) => {
    if (err) {
      console.error('[Auth] Logout error:', err);
      res.status(500).json({ error: 'internal_error', message: 'Logout failed' });
      return;
    }

    res.clearCookie('connect.sid');
    res.json({ success: true });
  });
});

/**
 * GET /api/auth/session
 * Check if user has an active session
 */
router.get('/session', optionalAuth, (req, res) => {
  res.json({
    authenticated: !!req.user,
    user: req.user ? {
      id: req.user.id,
      email: req.user.email,
      walletId: req.user.walletId,
    } : null,
  });
});

/**
 * POST /api/auth/login
 * Login with email and password
 */
router.post('/login', async (req, res) => {
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      res.status(400).json({
        error: 'validation_error',
        message: 'Email and password are required',
      });
      return;
    }

    // Find user by email
    const user = await prisma.walletUser.findUnique({
      where: { email: email.toLowerCase().trim() },
      select: {
        id: true,
        email: true,
        walletId: true,
        passwordHash: true,
        firstName: true,
        lastName: true,
      },
    });

    if (!user) {
      console.log(`[Auth] Login failed: user not found for ${email}`);
      res.status(401).json({
        error: 'invalid_credentials',
        message: 'Invalid email or password',
      });
      return;
    }

    // Check if user has a password set
    if (!user.passwordHash) {
      console.log(`[Auth] Login failed: no password set for ${email}`);
      res.status(401).json({
        error: 'no_password',
        message: 'No password set for this account. Please use passkey login or re-enroll to set a password.',
      });
      return;
    }

    // Verify password
    const passwordValid = await bcrypt.compare(password, user.passwordHash);

    if (!passwordValid) {
      console.log(`[Auth] Login failed: invalid password for ${email}`);
      res.status(401).json({
        error: 'invalid_credentials',
        message: 'Invalid email or password',
      });
      return;
    }

    // Set session
    req.session.userId = user.id;

    console.log(`[Auth] Login successful for ${email}`);

    res.json({
      success: true,
      user: {
        id: user.id,
        email: user.email,
        walletId: user.walletId,
        firstName: user.firstName,
        lastName: user.lastName,
      },
    });
  } catch (error) {
    console.error('[Auth] Login error:', error);
    res.status(500).json({
      error: 'internal_error',
      message: 'Login failed',
    });
  }
});

/**
 * GET /api/auth/sso
 * Single Sign-On endpoint - exchanges a JWT session token for a session cookie
 *
 * Query params:
 *   - token: JWT session token (returned from enrollment or payment flows)
 *   - redirect: Optional URL to redirect to after SSO (default: /wallet)
 *
 * This enables seamless wallet access after enrollment from BSIM.
 * The JWT is generated by auth-server during enrollment and shares the same JWT_SECRET.
 */
router.get('/sso', async (req, res) => {
  const token = req.query.token as string;
  const redirectTo = (req.query.redirect as string) || '/wallet';

  if (!token) {
    res.status(400).json({
      error: 'missing_token',
      message: 'Session token is required',
    });
    return;
  }

  try {
    // Verify the JWT token
    const payload = jwt.verify(token, env.JWT_SECRET) as jwt.JwtPayload;

    // Validate token has a subject
    if (!payload.sub) {
      throw new Error('Invalid token: missing subject');
    }

    const userId = payload.sub as string;

    // Verify user exists
    const user = await prisma.walletUser.findUnique({
      where: { id: userId },
      select: { id: true, walletId: true, email: true },
    });

    if (!user) {
      console.log(`[Auth SSO] User not found: ${userId}`);
      res.status(404).json({
        error: 'user_not_found',
        message: 'User not found. Your wallet may have been deleted.',
      });
      return;
    }

    // Create session
    req.session.userId = user.id;

    console.log(`[Auth SSO] User ${user.email} logged in via SSO token`);

    // Validate redirect URL (prevent open redirect)
    // Only allow relative paths starting with /
    const safeRedirect = redirectTo.startsWith('/') && !redirectTo.startsWith('//')
      ? redirectTo
      : '/wallet';

    // Redirect to frontend
    const frontendUrl = env.FRONTEND_URL;
    res.redirect(`${frontendUrl}${safeRedirect}`);
  } catch (error) {
    console.error('[Auth SSO] Token verification failed:', error);

    // Handle specific JWT errors
    if (error instanceof jwt.TokenExpiredError) {
      res.status(401).json({
        error: 'token_expired',
        message: 'Session has expired. Please log in again from your bank.',
      });
      return;
    }

    res.status(401).json({
      error: 'invalid_token',
      message: 'Invalid or expired session token. Please try again.',
    });
  }
});

export default router;
